### ISSUE TITLE
課題２　y=x-cosx

### ISSUE THREAD

**Issue by t190111** [nc2020/2-t190111#3]
<img width="960" alt="2020-04-24" src="https://user-images.githubusercontent.com/63433905/80196228-0fe2fe80-8658-11ea-9de3-b4b1cdc12683.png">

交点の値は、0.739085

**Comment by junta-m** [comment]
上のグラフから、解は0.739085と0.739090の間にあるとわかりますが、0.739085とするためには、目盛りがさらに必要です。

**Comment by t190111** [comment]
<img width="960" alt="2020-05-10" src="https://user-images.githubusercontent.com/63433905/81492002-1ebfe700-92cf-11ea-9d79-b52919ec13a9.png">

交点の値は、0.739085
